# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 887579472bb64b4b811cb2c002957e8f0f70db96f7d5f9cb5db8d2bd4875c6deae9aa3ad5673b468029697461e39c9c29112a57f03d2bc4ac64042e8d8d19ae2

test:
  secret_key_base: 338d8f3fabdd192a1a7c63f1790380ddc94d4a560a1dc99145446a37fa47888d3b0c9446c3663144df466ba49b90dbfc23cf5a52da3642082f91c5f2d4e1c304

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
