# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6de73ccf8ea320c45e98ccccfe01b905746aae77537b73b35739cf7136dce8d2648ab2df5016d74e794d5e7eb36520fdd43df93e6b91743b4b6871642991033

test:
  secret_key_base: 0bcb0eab724fe10dd7623a3295560d52e0bae413bffacb9d4d30940dbffcc264faad6b83741ed4689ea97363d5978f5100a525ff82cccc3eed93f0e3b9832b91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
