# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3db62ebd1c2902f8bd967ed585ee638d5b52243cbf9b2a1421aa5076c86b695a12177b1aa9214611e82f9638d681f9e25bbc4ee4a745484845d5eecd5387f84e

test:
  secret_key_base: e086db330100497e237c2ee2a244da3e979c1eae6ef35c12d9b09e33874d35acda4d86f2f3d37ecfc899caec183af5f18d69377682aace4469c0414d4a0304ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
